### PR TITLE
Add xiringuito - SSH-based "VPN for poors"

### PR DESCRIPTION
**Pull request by ivanilves**
Add xiringuito - SSH-based "VPN for poors"

# WHY?
`xiringuito` is awesome, because:
* easy to install (no dependencies, no configurations)
* allows you to manage one, few or many connections easily (and connect em simultaneously if you want)
* it has `xaval` connection manager - a tool that may record and later re-use your connection profiles
* though you are free to use or not to use `xaval` connection manager - people also use `xiringuito` for ad-hoc onetime connections
* Just look at this GIF :wink:

### CODE REVIEW

**Comment by ivanilves** [comment]
Hey :wave: 

Maybe merge this? :wink: 

ping @aloisdg

**Comment by ivanilves** [comment]
Closed due inactivity :ghost:

**Comment by aero31aero** [comment]
Hey @ivanilves it probably wouldn't hurt to leave this open. Maintainers sometimes get busy with work and when they do come online, they are likely to respond in bulk to the PRs made in there absence. :)

**Comment by ivanilves** [comment]
Hey, I think you are right! Reopened :+1:

**Comment by aloisdg** [comment]
Nice tool!

**Pull request merged**
