### PR TITLE
Added `DevOps-Bash-tools`

### PR DESCRIPTION
**Pull request by Rafat97**
#### New App Submission

- [x] I've read the [contribution guidelines](https://github.com/awesome-lists/awesome-bash/blob/master/contributing.md).

**Repo or homepage link:**
https://github.com/HariSekhon/DevOps-Bash-tools

**Description:**
DevOps Shell Scripts and Advanced Bash environment. You can see there summary [here](https://github.com/HariSekhon/DevOps-Bash-tools#summary)

**Why I think it's awesome:**
I think it's awesome because there has a tones of bash scripts that's made DevOps life easy .

### CODE REVIEW

**Comment by Knusper** [comment]
Hi, thats good ... for some reason I can not merge it ... who has the rights now?

**Comment by Rafat97** [comment]
@Knusper, Can you tell me, what's the reason, you can't merge?
If I do anything wrong let me know, I will try to solve.

**Comment by aloisdg** [comment]
@Knusper can you try to merge again?

**Comment by Knusper** [comment]
> @Knusper can you try to merge again?

Yes - now it works.  Thanks!

**Comment by aloisdg** [comment]
You are welcome :)

**Comment by Rafat97** [comment]
Thanks you for merging.

**Pull request merged**
