### PR TITLE
Learn Bash the Hard Way book, and a whitespace correction

### PR DESCRIPTION
**Pull request by ianmiell**
#### New App Submission

- [x] I've read the [contribution guidelines](https://github.com/awesome-lists/awesome-bash/blob/master/contributing.md).

**Repo or homepage link:**

https://leanpub.com/learnbashthehardway

**Description:**

Book to learn bash through typing out examples and thinking (the Hard Way method).

**Why I think it's awesome:**

Book - popular book on bash (I wrote it).

### CODE REVIEW

**Comment by aloisdg** [comment]
Hello,

Can you include links to positive discussions as per the following rule of the [contribution guidelines](https://github.com/awesome-lists/awesome-bash/blob/master/contributing.md)?

> Include links to positive discussions indicating this resource has a strong, positive community backing, e.g. a [Reddit](https://reddit.com/), [Hacker News](https://news.ycombinator.com/), [Lobster](https://lobste.rs/), or similiar post.

Thank you

**Comment by ianmiell** [comment]
Sure, sorry to overlook it:

https://twitter.com/remonsec/status/1302871118525595649

https://twitter.com/kuafu3/status/1034254459356864512

https://twitter.com/RHartmaier/status/968837880100610048

https://twitter.com/awizz_/status/951782150348656642

https://twitter.com/jonknox/status/1042699942492614656

https://twitter.com/thinkmassive/status/1519188045945257984

https://twitter.com/MsFaceless/status/1390568453338275840

as well as the amazon reviews:

https://www.amazon.com/Learn-Bash-Hard-Way-Master-ebook/dp/B078R24QPS/#customerReviews

**Comment by aloisdg** [comment]
* 4 mentions on reddit with the higher one at 2 upvotes and the lower one at -2 (mention to the person who recommend it without actually having read it).
* 14 reviews on amazon mostly positive which is quite good (well you [asked](https://nitter.pussthecat.org/ianmiell/status/957215792277450752#) for the positive ones but it is fine).
* 9 tweets about it mostly positive too. In 4 years though.

I have one more question is the book libre or open source itself? At least freely accessible in some way? Not being behind a paidwall is a huge +1 in my book.

It seems a bit light on the whole. We know that posting the book on the list will give it visibility, but the list is not here for that. I am not sure if the current state of community feedback is enough. Any opinion @knusper @bradrf ?

**Comment by ianmiell** [comment]
It's OK, I don't mind closing. It's good that you have rigorous standards.

**Comment by aloisdg** [comment]
Well it is hard to judge content and this one did look promising. You can try to post it to [HN](https://news.ycombinator.com/) or [lobste.rs](https://lobste.rs/) or even directly on reddit ([/r/bash](https://www.reddit.com/r/bash/), [/r/linux](https://www.reddit.com/r/linux), etc.

Be sure to respect the rules of each website, for /r/linux for example:

> Spamming self-promotion, surveys, crowdfunding - Submitting your own original content is welcome on [r/linux](https://www.reddit.com/r/linux), but we do ask that you contribute more than just your own content to the subreddit as well as require you to interact with the comments of your submission. We set that no more than 10% of your posts should be your content. Please be aware that this does not supersede other rules.

If the positive community feedback is broader, maybe someone else will submit it here. :)

Have a nice day

**Comment by ianmiell** [comment]
It's good. I already have many front pagers on HN (as zwischenzugs.com), they are indeed very sensitive to non-substantial content.
Keep up the good work!

**Pull request closed without merging**
