### PR TITLE
add progress-bar.sh

### PR DESCRIPTION
**Pull request by edouard-lopez**
Simple & sexy progress bar for bash, give it a duration and it will do the rest.

P.S. : I put a preview gif in the PR, tell me if it's annoying.

### CODE REVIEW

**Comment by aloisdg** [comment]
I like the gif. Could you use a smaller one (text's height would be perfect)? Keep it inline. You forget the separator between the name and the description. I am not sure why Simple is bold.

The project is cool. I like it, but it is quite young. I think it will be better to bullet proof it a bit before adding. If you agree, I will let the PR open for later. Try sharing it on /r/bash or /r/commandline maybe.

**Comment by edouard-lopez** [comment]
Done.
I'm ok too wait.
Thanks for the suggestion of `/r/bash`

**Comment by edouard-lopez** [comment]
bump, could you please merge or close?

**Comment by aloisdg** [comment]
done :)

**Pull request merged**
